# name: Zip and Deploy to S3

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Create ZIP archive
#       run: |
#         zip -r my-repo.zip . -x .git\*
#         echo "::set-output name=zip_path::my-repo.zip"

#     - name: Upload to S3
#       uses: jakejarvis/s3-sync-action@v0.3.0
#       with:
#         args: --acl private
#       env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
