# name: Deploy Lambda Function

# on:
#   push:
#     branches:
#       - main 

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.x

#       - name: Install dependencies
#         run: pip install -r lambda_function/requirements.txt

#       - name: Deploy Lambda
#         run: |
#           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
#           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
#           aws configure set region ap-southeast-1  # Change to your AWS region
#           sam deploy --template-file lambda_function/template.yaml --stack-name my-logging-service
#         env:
#           AWS_REGION: ap-southeast-1
